name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: "npm install"
        run: |
          cd docs
          npm ci
        env:
          CI: true
      - name: "npm build and deploy"
        run: |
          cd docs
          npm run build --if-present
          npm run deploy --if-present
        env:
          CI: true
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
